### ISSUE TITLE
Some Issue with repository or maven.

### ISSUE THREAD

**Issue by KrishnaST** [d3adspace/echidna#1]
I tried cleaning maven directory.

![image](https://user-images.githubusercontent.com/9427954/62998960-a553af00-be8a-11e9-8395-540c6c9cb4c7.png)

**Comment by felixklauke** [comment]
I will have to redeploy some legacy software for that to work. Echidna is currently not deployed in the repository as I'm working on a rewrite with much much better request handling. I can redeploy the old version if you want.

**Comment by KrishnaST** [comment]
Thanks. Waiting for it.
